cookie: BSESSIONID=.eJwljksOAjEIQO_StZNQSil9GQOlRLczzsp4dyfxAO_zKY_c1_Es1_d-rlt5vKLcS10LCcIYw1woeVaFFKcallMrexVL400cW6pN5IZBxDq0j1gyO08IJBmKNqQPSAR05J4U1urEgOYQ4mmXvq2UCJRFnbuxlWvkPNb-v5mY0IhwG1a-UVXZHDK2C-IaoFeCy_cHGSw45g.ZBnKog.LzXxDvQLs-fRCcGSeXhYGiIB6JU
password: root12345
project_id: d6b65b58-e2f4-4ce6-8293-06ca9eba3c40
server: http://127.0.0.1:8080
username: root@ro.ot
